-- CREATE TABLE product (
--     id serial PRIMARY KEY,
--     name varchar(255) NOT NULL,
--     price numeric(10,2) NOT NULL,
--     created_at timestamp NOT NULL DEFAULT NOW(),
--     updated_at timestamp NOT NULL DEFAULT NOW()
-- );
