-- CREATE TABLE product (
--     id INT NOT NULL AUTO_INCREMENT,
--     name VARCHAR(255) NOT NULL,
--     price DECIMAL(10,2) NOT NULL,
--     description TEXT,
--     image VARCHAR(255),
--     PRIMARY KEY (id)
-- );
